起動時にテーブル作成
mottanCopen/yuiman_workshop pull request #4
Opened 2022-07-17 05:58 UTC by mottanCopen

起動時にテーブル作成されるようにdocker-compose.ymlを修正
DDLのSQLを記述したinit.sqlを追加

2022-07-17 07:35 UTC, y4ml reviewed
sqlはデータベースへの自動投入はされるのでしょうか

2022-07-17 07:37 UTC, mottanCopen commented
起動した時にSQL実行されるはずです

2022-07-17 07:44 UTC, y4ml commented
> 起動した時にSQL実行されるはずです

こちらDockerfileが別途あるのでしょうか。
pullしただけでは手元で起動しませんでした。
動作確認のほうはされましたか？

2022-07-17 07:46 UTC, mottanCopen commented
docker再起動しましたか？

2022-07-17 13:07 UTC, mottanCopen commented
できましたか？

2022-07-17 13:54 UTC, y4ml commented
> できましたか？

出来ましたがそのままでは出来なかったため、コメントの対応をお願いします。

2022-07-17 15:11 UTC, y4ml requested changes

2022-07-17 15:11 UTC, y4ml commented on docker/postgresql/init/init.sql
> +\c postgres
デフォルトで用意されているデータベースにテーブルを配置するのではなく、 `yuiman`のような別途自身で用意したデータベース配下に置いた方が良いかと思いました。

2022-07-17 15:11 UTC, y4ml commented on docker/docker-compose.yml
> +    build: ./postgresql
buildはそもそも必要ですか？

2022-07-18 06:26 UTC, mottanCopen commented
修正しました。

2022-07-18 08:09 UTC, y4ml approved these changes

2022-07-18 10:03 UTC, merged